language: elixir
sudo: false

elixir:
  - 1.7
otp_release:
  - 21.0

before_script:
  - make pull_deps
  - make linter

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report

after_success:
  - bash <(curl -s https://codecov.io/bash)