language: elixir
sudo: false

branches:
  only:
    - master

before_script:
  - mix local.hex --force
  - mix deps.get --only test

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report

elixir:
  - 1.6.6
  - 1.7.1
otp_release:
  - 20.0
  - 21.0

matrix:
  include:
    - elixir: 1.6.6
      otp_release: 20.0
    - elixir: 1.7.1
      otp_release: 20.0
    - elixir: 1.7.1
      otp_release: 21.0